server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape docker logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/lib/docker/containers/*/*-json.log
    
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
            time: time
            container_name: attrs.container_name
            image_name: attrs.image_name
      
      # Extract Docker container name and image from the log path
      - regex:
          expression: '/var/lib/docker/containers/(?P<container_id>[^/]+)/'
      
      - timestamp:
          source: time
          format: RFC3339Nano
      
      - labels:
          stream:
          container_id:
          container_name:
          image_name:
      
      - output:
          source: output