server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 102400
    timeout: 10s

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'job'
        replacement: '${1}'
    
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/lib/docker/containers/*/*log

    # Extraemos información importante de los logs
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      
      # Parseamos logs JSON
      - regex:
          expression: '(?P<ip>\d+\.\d+\.\d+\.\d+).*?(GET|POST|PUT|DELETE) (?P<endpoint>[^ ]*) HTTP.*?(?P<status>\d{3})'
          source: log
      
      # Añadimos etiquetas para facilitar búsquedas y alertas
      - labels:
          ip:
          endpoint:
          status: