services:
  # Load Balancer
  loadbalancer:
    build: ./loadbalancer
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend1
      - backend2
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - frontend-network
    restart: unless-stopped

  # Frontend - React
  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_API_URL=/api
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - frontend-network
    restart: unless-stopped

  # Backend 1
  backend1:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - FRONTEND_URL=http://frontend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend 2
  backend2:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - FRONTEND_URL=http://frontend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uappuser", "-papppassword"]
      interval: 5s
      timeout: 10s
      retries: 10

  # Database Admin
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend-network
    environment:
      - ADMINER_DEFAULT_SERVER=db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  # Docker Admin
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    security_opt:
      - no-new-privileges:true

volumes:
  mysql_data:
  portainer_data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
    internal: true